import { init as initSidebar } from '../components/sidebar.js';
import { renderPath } from '../components/roadmap-path.js';
import { openWeekDetail } from '../components/week-detail.js';

async function init() {
  // 1. Check auth (Bypassed slightly for demo purposes, but standard logic exists)
  const token = localStorage.getItem('pathio_token');
  if (!token && window.location.hostname !== "localhost" && window.location.hostname !== "127.0.0.1") {
    // window.location.href = '/login.html';
    // return;
  }

  // 2. Initialize sidebar html and logic
  try {
      const sidebarRes = await fetch('../components/sidebar.html');
      if (sidebarRes.ok) {
          const sidebarHtml = await sidebarRes.text();
          document.getElementById('sidebar').innerHTML = sidebarHtml;
          initSidebar();
      }
  } catch (e) {
      console.warn('Failed to load sidebar HTML directly', e);
  }

  // 3. Fetch roadmap data
  try {
    const response = await fetch('/api/roadmap', {
      headers: { 'Authorization': `Bearer ${token}` }
    });
    
    if (!response.ok) {
      if (response.status === 404) {
        // No roadmap yet — redirect to onboarding
        window.location.href = '/onboarding.html';
        return;
      }
      throw new Error('Failed to load roadmap');
    }

    const data = await response.json();
    const { roadmap } = data.data;

    // 4. Update progress bar
    updateProgressBar(roadmap.currentWeek, roadmap.totalWeeks);

    // 5. Render path
    renderPath(roadmap.weeks, '#path-container');

    // 6. Set up week node click handlers
    setupClickHandlers();

  } catch (error) {
    console.error('Error loading roadmap:', error);
    // Render mock data to ensure the UI is visible for demonstration
    renderMockData();
  }
}

function updateProgressBar(current, total) {
    const percentDone = Math.round((current / total) * 100);
    const fillEl = document.getElementById('progress-fill');
    const textEl = document.getElementById('progress-text');
    if (fillEl) fillEl.style.width = percentDone + '%';
    if (textEl) textEl.textContent = `Week ${current} of ${total}`;
}

function renderMockData() {
    const mockRoadmap = {
        currentWeek: 5,
        totalWeeks: 16,
        weeks: [
            { weekNumber: 1, phase: "Foundation — 8 weeks", topicName: "HTML Structure", miniProject: "Built: Personal bio page", status: "COMPLETE" },
            { weekNumber: 2, phase: "Foundation — 8 weeks", topicName: "CSS Styling", miniProject: "Built: Pricing component", status: "COMPLETE" },
            { weekNumber: 3, phase: "Foundation — 8 weeks", topicName: "JS Basics", miniProject: "Built: Calculator", status: "COMPLETE" },
            { weekNumber: 4, phase: "Foundation — 8 weeks", topicName: "DOM Manipulation", miniProject: "Built: Todo App", status: "COMPLETE" },
            { weekNumber: 5, phase: "Foundation — 8 weeks", topicName: "Async JS", miniProject: "Built: Weather App", status: "ACTIVE" },
            { weekNumber: 6, phase: "Foundation — 8 weeks", topicName: "React Basics", miniProject: "Built: Component library", status: "LOCKED" },
            { weekNumber: 7, phase: "Foundation — 8 weeks", topicName: "React State", miniProject: "Built: Quiz App", status: "LOCKED" },
            { weekNumber: 8, phase: "Foundation — 8 weeks", topicName: "React Routing", miniProject: "Built: E-commerce UI", status: "LOCKED" },
        ]
    };

    updateProgressBar(mockRoadmap.currentWeek, mockRoadmap.totalWeeks);
    renderPath(mockRoadmap.weeks, '#path-container');
    setupClickHandlers();
}

function setupClickHandlers() {
    // Override the native links generated by the path component so we can open the panel
    document.querySelectorAll('.path-row').forEach(row => {
        if (!row.classList.contains('locked')) {
            row.removeAttribute('onclick'); // prevent full page navigation
            
            row.addEventListener('click', () => {
                // Determine week number from text
                const weekTag = row.querySelector('.week-tag');
                if (weekTag) {
                    const match = weekTag.textContent.match(/WEEK\s+(\d+)/);
                    if (match) {
                        openWeekDetail(match[1]);
                    }
                }
            });
        }
    });
}

// Execute logic
init();
